sudo: false
language: python
python: '2.7'
#before_install:
#  - docker build -t tailor -f travis-Dockerfile .
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_change: always
